microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENTSERVICE/payment/savePaymentDetails
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDERSERVICE/order/saveOrder
